name: Stephen Roberts
title: Full Stack Software Engineer
meta:
  description: Full stack software engineer solving the world's problems one line of code at a time. HTML, CSS, JavaScript, NodeJS, AWS, serverless, microservices, craftsman.
  keywords: full stack software engineer, web developer, javascript, html, css, aws, linux, microservices, craftsmanship, serverless, linux, continuous integration, deployments, rest api
socials:
  github: https://github.com/stephencroberts/
  facebook: https://www.facebook.com/stephencroberts/
  twitter: https://twitter.com/StephenCRoberts/
  googleplus: https://plus.google.com/u/0/111435975431163827155/

menu:
  Skills: "#skills-anchor"
  Experience: "#experience-anchor"
  Education: "#education-anchor"
  Environment: "#environment-anchor"
  References: "#references-anchor"
  Contact: "#contact-anchor"

about:
  summary: "Software engineering is the intersection of two of my passions: computer technology and problem-solving. I am passionate about finding and implementing the best technical solution to achieve a business objective, considering complexity, scalability, security, lifetime, budget, time, and skill set of the team. Creating a team with a healthy culture that encourages ownership, creativity, coaching/mentorship, and continual learning is essential to creating high-quality solutions. I thrive on new challenges and am constantly learning. With a wide range of experience across many languages, platforms, and frameworks and exposure to many design concepts, I'm always prepared to tackle something new. I believe strongly in a few core concepts:"
  details:
    - Business objectives/requirements should dictate the technology stack rather than making a particular tech stack try to fit all projects
    - Software should be written with the long-term vision and goals in mind to aid in decisions about architecture, tests, documentation, and maintainability
    - Complex problems should be broken down into smaller problems that can be more easily reasoned about and transformed into code that is more understandable and maintainable
    - Properly designed systems and architectures create momentum as new products and features are created

skills:
  General Expertise:
    microservices: Microservices and System Architectures
    serverless: Serverless Architectures
    devops: DevOps and Release Management
    apis: APIs
    web: Web Apps
    mobile: Mobile Apps
    analytics: Analytics
    performance: Performance
  Technology:
    javascript: nodejs, ES2015
    html: HTML5
    css: CSS3
    aws: AWS
    linux: UNIX, Linux
    bash: Shell Scripting
    ios: iOS, Objective-C, Swift
    ruby: Ruby, Ruby on Rails
    php: PHP, Joomla!, Wordpress
    java: Java
    document: XML, JSON
    sql: SQL, No-SQL
    c: ANSI C, C++
    dotnet: C#, .NET
  Tools:
    editor: vim
    shell: unix shell
    vcs: git
    ios: XCode
    graphics: Photoshop
    automation: Terraform, Chef, CloudFormation
    vm: Vagrant
    ci: GitLab CI, Jenkins, Travis CI
    task-runners: Webpack
    dependency-managers: Dependency Managers

experience:
  - title: DevOps Engineer
    company: DaVita
    date: January 2019 - Present
    summary: Part of a transformational engineering team focused on helping the organization adopt engineering practices through modern tools, principles, and techniques
    details:
      - Coached and mentored teammates to help the organization transition to the Google Cloud Platform
      - Consulted with other teams to aid in software and system design in the cloud
      - Developed the core automation for deploying infrastructure-as-code with Terraform
      - Created tooling to improve automation around terraform using a variety of shell scripting, jq, and golang
      - Deployed core shared services critical to developing and operating software securely such as GitLab, Vault, and Artifactory
      - Developed Google Cloud Functions as supplemental tooling around cloud automation
      - Aided in deploying Google Kubernetes Engine using terraform
      - Deployed OpenFaas and functions on-premises, demonstrating a serverless approach to on-premises automation
      - Demonstrated insfrastructure-as-code on-premises using terraform with VMware vSphere
  - title: Principal Engineer
    company: Sling TV, part of DISH Network
    date: June 2017 - August 2018
    summary: Led a large, long-term initiative to build an e-commerce cart for the main website
    details:
      - Led the core team to design and create the cart engine, consolidating complexity into a small amount of code, enabling a simple, modular cart
      - Led the cart initiative with over 30 developers and QA resources, providing design direction, coaching/teaching, and collaborating with various business and technical groups to remove blockers and keep the project on track
      - Implemented the cart engine with React/Redux, following a functional design
      - Created a framework for a distributed frontend (micro-frontend) at runtime with JavaScript
      - Helped create and guide a collaborative effort to create a functional React component library (UIKit)
      - Created an automated semantic versioning framework for the UIKit, determining the next version based on analyzing code changes and visually diffing the components
      - Created a "service templates" framework using Yeoman as the source of truth for creating/managing projects, inverting the control of distributing updates
      - Created a dockerized testing framework for automation, supporting selenium grid, webdriver.io, cucumberjs, and newman
      - Collaborated with DevOps to create and streamline continuous integration pipelines
      - Helped shape the automation and process to transition from cutting releases to feature delivery
      - Presented at community of practice meetings to further education and collaboration across teams
      - Created a generic pluggable analytics plugin in JavaScript to abstract analytics implementations and enable more rich and robust data collection
      - Created an nginx reverse proxy to support dynamic review environments (a different environemnt per feature branch)
      - Created a framework for a microfrontend admin portal in React/Redux
      - Contributed to design/vision/process discussions for the organization
  - title: Developer
    company: Manheim, a Cox Automotive company
    date: January 2017 - May 2017
    summary: Developed Java microservices using the Spring Boot framework for high-traffic, high-availability applications
    details:
      - Developed a web application using Thymeleaf for displaying report information
      - Improved internal development tools and processes
      - Implemented new features and bug fixes to existing applications
  - title: Lead Full Stack Web Engineer
    company: FIDOlab
    date: March 2015 - October 2016
    summary: Designed and developed full-stack web applications and mobile backends focusing on a microservices approach, serverless architectures in AWS, automation, release management, and automated testing
    details:
      - Developed an entertainment web app, PluggedIn.com, in AngularJS using standard task runners, preprocessors, and automated build and delivery pipelines including unit, end-to-end, and visual tests
      - Provisioned infrastructure with Chef
      - Created microservices using AWS serverless resources with APIs for use in multiple web and mobile applications
      - Developed a native iOS application in Swift with offline support, media player integration, and In-App Purchases with a custom IAP backend (built as a microservice) to deliver purchased resources to the app
      - Migrated mobile applications from using Parse mobile BaaS to using AWS resources
      - Worked with the team to create an agile development workflow that fit our small team and goals
      - Helped other developers and contractors with code-review, software architecture, and backend services
  - title: Web Developer
    company: Focus on the Family
    date: January 2014 - March 2015
    summary: Developed web and mobile applications on a variety of different languages, platforms, and frameworks, working with the team to successfully complete business objectives within the given time constraints
    details:
      - Developed a framework and dashboard for in-house Wordpress developers to deploy Wordpress sites to multiple environments and standardized workflow for local development, dependency management, deployments, and source control
      - Co-developed an iOS app, focusing on integration with the backend and various 3rd party services, extending the back end (a generated Ruby on Rails app) to add custom functionality, developing parts of the iOS UI, and creating an automated deployment pipeline for the backend
      - Added features and fixed bugs in an existing webapp built with CakePHP and BackboneJS
      - Developed a jQuery plugin as a popup for giving campaigns including A/B testing and user data capture, implemented in Sitecore CMS using Microsoft .NET
      - Developed minor features and changes to Sitecore CMS sites
  - title: Owner
    company: DigiToll Software
    date: May 2012 - December 2015
    details:
      - Created and managed every aspect of a small software product company including design, development, maintenance, marketing, sales, customer service, and financials
      - Developed extensions in PHP for Joomla! and VirtueMart with a focus on digital downloads and delivery
  - title: Owner
    company: Stephen Roberts LLC
    date: February 2011 - October 2015
    summary: Worked with clients to develop e-commerce websites, perform content migrations, and integrate with existing systems
    details:
      - Added e-commerce and digital download capability to an existing website built on Joomla! CMS
      - Developed a new e-commerce website using Joomla! and VirtueMart for the sale of physical products, migrated the product catalog from the existing IBM WebSphere platform, and integrated with existing inventory and ERP systems
      - Collaborated with marketers and designers to create another e-commerce website selling both physical and digital downloads
  - title: Engineering Technician Assistant
    company: University of South Alabama
    date: September 2007 - December 2010
    summary:
    details:
      - Computer and Lab Technician supporting 12 Computer and Technical Labs
      - Installed software, performed system backups, and maintained over 175 computers
      - Repaired Oscilloscopes, Power Supplies, Digital Systems, and other lab equipment

education:
  - institution: University of South Alabama
    degree: BS in Computer Engineering
    date: 2005-2009
    memberships:
      - Tau Beta Pi
      - IEEE
      - Eta Kappa Nu
    courses:
      - Computer Network Security
      - Digital Computer System Design
      - Electrical & Computer Engineering Design
      - Programming Language Theory
      - Computer Networks
      - Embedded System Design
      - Software Engineering Principles
      - Wireless Networks
      - Analog & Digital Electronics
      - Computer Methods In ECE
      - Microprocessors
      - Operating Systems
      - Data Structures

environment:
  tools: iterm2 + tmux + vim
  dotfiles: https://github.com/stephencroberts/dotfiles

references:
  - name: Mike Ruman, Military Marketing
    quote: When others would say ‘that’s too hard’ or ‘I’m not sure I could do that’ Stephen would respond with ‘let me think through this and put together a plan.'...Stephen rose to the occasion and did his best to make sure the projects were completed on time and met the requirements...Stephen did a great job communicating

